### ISSUE TITLE
[DataCap Application] <datastorage> - < datastorage >

### ISSUE THREAD

**Issue by 1613557499** [filplus-bookkeeping/Bewell-Technology-Limited#3]
### Version

1

### DataCap Applicant

Dataset Owner

### Project ID

2

### Data Owner Name

K12 International Education Platform

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

http://www.topschools.cn/index?_l=en

### Social Media Handle

顶思

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

512TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f16xgqbyk4fonenyxqfgik3qf2odr73ws7rqnisca

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TopSchools was founded on August 28, 2016.  As the resource aggregation platform of K12 international Education, TopSchools is committed to supporting the sustainable development of the international school market through community communication, data research, teacher training and talent recruitment.  Topschools is a close partner of international schools and international education institutions.  Provides industry with information on international education policies, operations, investments, schools, and people.  Organized various online and offline activities, cooperated with various examination bureaus, global top universities, research institutions, embassies and consulates, and provided services and support for more than 600 schools across the country;  We are linked to thousands of quality school service providers around the world to provide a variety of solutions for schools.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Our data is very large, mainly stored all kinds of courses of teaching videos, materials, documents.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We plan to cooperate and negotiate with professionals to ensure the safety and reliability of data, and achieve short-term or long-term effective storage to ensure the integrity of data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have previously applied for 1p data, that data is only a small part of our total data, the company's development is stable, our data is always growing, storage costs are also increasing, the need for filecoin network support, for the development of the traditional Internet industry to promote.
```

### Please share a sample of the data

```text
https://pan.baidu.com/s/1vOQ-h6lCCLvCXAY_PtsP1A?pwd=6jt9 
https://pan.baidu.com/s/1CbRHk1E-tiXULoJIgLawMw?pwd=iapx 
https://pan.baidu.com/s/1_qSCseiHfUPyXFumfgvsLQ?pwd=fgis
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How did you find your storage providers

Slack, Filmine, Big Data Exchange, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02850067
fo2830476
fo2941888
fo2950965
fo2830451
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Aaron01230** [comment]
I noticed that this is a public large data set. Have you ever applied for an LDN storage project for this before? Have you found a cooperative SPs? Please disclose the SP information

**Comment by 1613557499** [comment]
I have applied before. Please check the link below
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2283
sp：
f03028321
f03028310
f03028318

**Comment by Aaron01230** [comment]
Pls send a email to verify the LDN is applied from the enterprise

**Comment by 1613557499** [comment]
<img width="391" alt="image" src="https://github.com/filplus-bookkeeping/Bewell-Technology-Limited/assets/86406225/c1728e98-af59-404b-9587-1f69eae9ccb9">

**Comment by 1613557499** [comment]
> Pls send a email to verify the LDN is applied from the enterprise

Who is the recipient of the email?

**Comment by 1613557499** [comment]
> Pls send a email to verify the LDN is applied from the enterprise

<img width="798" alt="image" src="https://github.com/filplus-bookkeeping/Bewell-Technology-Limited/assets/86406225/19b6d040-ae71-41f8-9a60-814ec0b3027f">

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by 1613557499** [comment]
checker:manualTrigger
